export { default as Navbar } from './Navbar'
export { default as Home } from './Home'
export { default as Products } from './Products'
export { default as SearchComponent } from './SearchComponent'
export { default as Product } from './Product'
export { default as CartProducts } from './CartProducts'
export { default as CheckoutPage } from './CheckoutPage'
export { default as SingleProduct } from './SingleProduct'
